version: '2'
services:
  php:
    image: bscheshir/php:7.3.5-fpm-alpine-4yii2
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  php-supervisor: # for workers
    image: bscheshir/php:7.3.5-fpm-alpine-4yii2-supervisor
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ./supervisor-conf:/etc/supervisor/conf.d
      - ./supervisor-logs:/var/log/supervisor
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  redis:
    image: redis:5.0.4-alpine
    restart: always
    command: redis-server /etc/redis/conf.d/redis.conf --requirepass yii2advancedredis
    ports:
      - "6379"
    volumes:
      - ./redis-data:/data
      - ./redis-conf:/etc/redis/conf.d
    depends_on:
      - php-supervisor
    environment:
      TZ: Europe/Moscow
  nginx:
    image: nginx:1.15.12-alpine
    restart: always
    expose:
      - "8080"
      - "8081"
#    ports: # use nginx-proxy in same network (see ./docs/nginx-proxy.md)
#      - "8080:8080"
#      - "8081:8081"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
    environment:
      TZ: Europe/Moscow
  db:
    image: mysql:8.0.16
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
