version: '2'
services:
  php:
    image: bscheshir/php:7.1.8-fpm-alpine-4yii2
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  php-supervisor: # for workers
    image: bscheshir/php:7.1.8-fpm-alpine-4yii2-supervisor
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ./supervisor-conf:/etc/supervisor/conf.d
      - ./supervisor-logs:/var/log/supervisor
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_enable=Off remote_autostart=Off"
  redis:
    image: redis:4.0.1-alpine
    command: redis-server --requirepass yii2advancedredis
    ports:
      - "6379"
    volumes:
      - ./redis-data:/data
    depends_on:
      - php-supervisor
  nginx:
    image: nginx:1.13.3-alpine
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ./nginx-logs:/var/log/nginx #nginx-logs
  db:
    image: mysql:8.0.2
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always
    volumes:
      - ./mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
