version: '3.7'
services:
  php:
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2-xdebug
    restart: always
    volumes:
      - ../php-data:/var/www/html #php-data
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT} remote_enable=On var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
  php-supervisor: # for workers
    image: bscheshir/php:7.4.3-fpm-alpine-4yii2-supervisor-xdebug
    restart: always
    volumes:
      - ../php-data:/var/www/html #php-data
      - ../supervisor-conf:/etc/supervisor/conf.d
      - ../supervisor-logs:/var/log/supervisor
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT_SUPERVISOR} var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
  redis:
    image: redis:5.0.7-alpine
    restart: always
    command: redis-server /etc/redis/conf.d/redis.conf --requirepass yii2advancedredis
    ports:
      - "6379"
    volumes:
      - ../redis-data-test:/data
      - ../redis-conf:/etc/redis/conf.d
    depends_on:
      - php-supervisor
    environment:
      TZ: Europe/Moscow
  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ../php-data:/var/www/html #php-data
      - ../nginx-conf-test:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    networks:
      default:
      selenium-nginx:
        aliases:
         - backend.nginx
         - frontend.nginx
    environment:
      TZ: Europe/Moscow
  db:
    image: mysql:8.0.19
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password' # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - ../mysql-data-test/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
  codecept:
    image: bscheshir/codeception:php7.4.3-fpm-alpine-yii2
    depends_on:
      - nginx
      - browser
    volumes:
      - ../php-data:/var/www/html #php-data
    networks:
      - default
      - selenium-nginx
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT_CODECEPTION} remote_enable=On"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME_CODECEPTION}"
  browser:
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
      - /dev/shm:/dev/shm # the docker run instance may use the default 64MB, that may not be enough in some cases
    networks:
      - selenium-nginx
    ports:
      - '4444'
      - '5900'
    environment:
      TZ: Europe/Moscow
networks:
  selenium-nginx:
