version: '2'
services:
  php:
    image: bscheshir/php:7.1.11-fpm-4yii2-xdebug
    restart: always
    volumes:
      - ../php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9001 remote_enable=On var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=yii2advanced"
  php-supervisor: # for workers
    image: bscheshir/php:7.1.10-fpm-alpine-4yii2-supervisor-xdebug
    restart: always
    volumes:
      - ../php-code:/var/www/html #php-code
      - ../supervisor-conf:/etc/supervisor/conf.d
      - ../supervisor-logs:/var/log/supervisor
    depends_on:
      - db
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9003 var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=yii2advanced"
  redis:
    image: redis:4.0.2-alpine
    restart: always
    command: redis-server /etc/redis/conf.d/redis.conf --requirepass yii2advancedredis
    ports:
      - "6379"
    volumes:
      - ../redis-data:/data
      - ../redis-conf:/etc/redis/conf.d
    depends_on:
      - php-supervisor
  nginx:
    image: nginx:1.13.6-alpine
    restart: always
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ../nginx-conf-test:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
    networks:
      default:
        aliases:
         - backend.dev
         - frontend.dev
  db:
    image: mysql:8.0.3
    entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - ../mysql-data-test/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: yii2advanced
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: yii2advanced
  codecept:
    image: bscheshir/codeception:php7.1.11-fpm-yii2
    depends_on:
      - nginx
      - browser
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=192.168.0.83 remote_port=9002 remote_enable=On"
      PHP_IDE_CONFIG: "serverName=codeception"
    volumes_from:
      - php
  browser:
    image: selenium/standalone-chrome-debug:3.7.1
#    image: selenium/standalone-firefox-debug:3.7.1
    volumes:
      - /dev/shm:/dev/shm # the docker run instance may use the default 64MB, that may not be enough in some cases
    ports:
      - '4444'
      - '5900'
